name: finance-app-monolith

services:
  finance-service:
    build: finance-app
    image: finance-app:2.0.5
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - finance-network
  pg_db:
    build: postgresql
    image: postgresql-finance:2.0.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - finance-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@finance.com
      PGADMIN_DEFAULT_PASSWORD: finance
    ports:
      - 82:80
    networks:
      - finance-network
  proxy:
    build: proxy
    image: proxy-finance:2.0.1
    ports:
      - 80:80
    networks:
      - finance-network

networks:
  finance-network: