spring:
  application:
    name: finance-app
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_monolith
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: app
#Custom properties
application:
  pagination:
    minPageSize: 2
    maxPageSize: 30
  jwt:
    secret: BgKSLkg!oFKAjs1m^mm!sfsGmZQs;k1L!
    issuer: ITAcademy
