spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_monolith
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20

application:
  verification:
    url: http://localhost:8080/cabinet/verification
