spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://pg_db:5432/finance_monolith
    username: postgres
    password: postgres

application:
  verification:
    url: http://localhost/api/v1/cabinet/verification